apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: privicypal-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/privicypal-cluster: "owned"
    desiredCapacity: 2
    instanceType: t2.micro
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true

git:
    repo:
        url: "git@github.com:privicy/privicypal-cluster.git"
        branch: master
        fluxPath: "flux/"
        user: "gitops"
        email: "stevenroussey-privicy@users.noreply.github.com"
    operator:
        namespace: "flux"
        withHelm: true
    bootstrapProfile:
      source: app-dev
      revision: master
      
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: db-access
      namespace: application
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess"
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    attachPolicy: # inline policy can be defined along with `attachPolicyARNs`
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        Resource: '*'

