apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: privicypal-cluster
  region: us-east-2

git:
  repo:
      url: "git@github.com:privicy/privicypal-cluster.git"
      branch: master
      fluxPath: "flux/"
      user: "gitops"
      email: "stevenroussey-privicy@users.noreply.github.com"
  operator:
      namespace: "flux"
      withHelm: true
  # bootstrapProfile:
  #   source: app-dev
  #   revision: master